# Generated by Django 5.2.8 on 2025-11-18 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('siret', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('numero_securite_sociale', models.CharField(blank=True, max_length=15, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_entree', models.DateField(blank=True, null=True)),
                ('type_contrat', models.CharField(blank=True, max_length=50, null=True)),
                ('temps_travail', models.CharField(blank=True, max_length=50, null=True)),
                ('poste', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='social.client')),
            ],
        ),
    ]
