# Generated by Django 5.2.8 on 2025-11-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_client_activite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ape',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='representant_legal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='siren',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='siret',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
