# Generated by Django 5.2.8 on 2025-11-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_client_ape_alter_client_representant_legal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarie',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='salarie',
            name='temps_travail',
        ),
        migrations.RemoveField(
            model_name='salarie',
            name='type_contrat',
        ),
        migrations.AddField(
            model_name='salarie',
            name='code_civilite',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='salarie',
            name='code_commune_naissance',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='salarie',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='salarie',
            name='code_reglement',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='salarie',
            name='commune_naissance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salarie',
            name='emploi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salarie',
            name='nationalite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salarie',
            name='nom_marital',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salarie',
            name='nom_voie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salarie',
            name='num_voie',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='salarie',
            name='pays_naissance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salarie',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salarie',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salarie',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salarie',
            name='numero_securite_sociale',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salarie',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
    ]
